openapi: 3.1.0
info:
  title: Google CSE Plugin
  version: "1.0.0"
servers:
  - url: https://www.googleapis.com/customsearch/v1

paths:
  /:
    get:
      operationId: search
      summary: Buscar en Google Custom Search
      security:
        - ApiKeyAuth: []
      parameters:
        - in: query
          name: cx
          required: true
          schema:
            type: string
          description: Tu Search Engine ID (CX)
        - in: query
          name: q
          required: true
          schema:
            type: string
          description: El texto que quieras buscar
      responses:
        "200":
          description: Resultados de búsqueda
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: key
  schemas: {}
